version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    environment:
      - DB_PATH=/app/data/auth.db
      - JWT_SECRET=mi-clave-secreta-super-segura-2024
      - PEPPER=mi-pepper-secreto-2024
    volumes:
      - auth_data:/app/data

  image-service:
    build:
      context: ./image-service
      dockerfile: Dockerfile
    ports:
      - "8082:5000"
    volumes:
      - image_data:/root/uploads
    depends_on:
      - auth-service

volumes:
  auth_data:
  image_data: